"""
biodreamer.hub.upload — Push Models to Hugging Face Hub.

Purpose:
    Uploads trained BioDreamer models (world models, policies, reward heads)
    to Hugging Face Hub with auto-generated model cards, making them available
    for the community and for the web frontend's model browser.

Components to implement:
    - upload_model(model, model_id, model_card, metrics, private=False):
        Serialises the PyTorch model + config + model card and pushes to HF Hub.

    - upload_checkpoint(checkpoint_dir, model_id):
        Uploads a full training checkpoint (model weights + optimiser state +
        training config) for resumable training.

    - create_repo_if_needed(model_id, private):
        Creates the HF Hub repository if it doesn't exist.

Design notes:
    - Uses huggingface_hub.HfApi for all Hub operations.
    - Models are saved as safetensors (preferred) or torch .pt files.
    - The model card (auto-generated by hub/model_card.py) is pushed alongside.
    - Requires HF_TOKEN environment variable with write access.
    - Support tagging models with domain (protein-dreamer, mol-dreamer, cell-dreamer)
      and model type (world-model, policy, encoder).
"""
